en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Leon Environmental Caucus"
  title: "Leon Environmental Caucus"
  params:
    description: "A chapter of the Democratic Environmental Caucus of Florida, chartered by the Florida Democratic Party"
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
    #   help_text: "Accessibility Statement"
    #   help_url: "/accessibility/"
    ### calls to action ###
    main_cta:
      text: "Donate"
      link: "/donate/"
    footer_cta:
      text: "Donate"
      link: "/donate/"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 2
    - identifier: "mission"
      name: "Our Mission"
      url: "/mission/"
      weight: 1
      parent: "about"
    - identifier: "who-we-are"
      name: "Who We Are"
      url: "/who/"
      weight: 2
      parent: "about"
    - identifier: "website"
      name: "Our Website"
      url: "/website/"
      weight: 3
      parent: "about"
    - identifier: "participate"
      name: "Participate"
      url: "/participate/"
      weight: 3
    - identifier: "donate"
      name: "Donate"
      url: "/donate/"
      weight: 1
      parent: "participate"
    - identifier: "volunteer"
      name: "Volunteer"
      url: "/volunteer/"
      weight: 2
      parent: "participate"
    - identifier: "join"
      name: "Join Us"
      url: "/join/"
      weight: 3
      parent: "participate"
    - identifier: "events"
      name: "Events" 
      url: "/events/"
      weight: 4
      parent: "participate"
    - identifier: "endorsements"
      name: "Endorsements"
      url: "/endorsements/"
      weight: 4
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 5
    - identifier: "links"
      name: "Links"
      url: "/links/"
      weight: 6
    - identifier: "contact"
      name: "Contact"
      url: "/contact/"
      weight: 7
es:
  copyright: "Copyright &copy; {{< current_year >}} Leon Environmental Caucus"
  title: "Caucus Ambiental Democrático del Cantón de León"
  languageName: Spanish
  contentDir: content/es
  weight: 2
  params:
    description: "A chapter of the Democratic Environmental Caucus of Florida, chartered by the Florida Democratic Party"
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
    ### calls to action ###
    # main_cta:
    #   text: "Donate"
    #   link: "/donate/"
    # footer_cta:
    #   text: "Donate"
    #   link: "/donate/"
  menu:
    main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1
    - identifier: "rights"
      name: "Information About Your Rights"
      url: "/information-about-rights"
      weight: 2
