en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} Leon Environmental Caucus"
  title: "Leon Environmental Caucus"
  params:
    description: "A chapter of the Democratic Environmental Caucus of Florida, chartered by the Florida Democratic Party"
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      help_text: "Accessibility Statement"
      help_url: "/accessibility/"
    ### calls to action ###
    main_cta:
      text: "Join Us"
      link: "/join/"
    footer_cta:
      text: "Join Us"
      link: "/join/"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "home"
      name: "Home"
      url: "/"
      weight: 1
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 2
    - identifier: "mission"
      name: "Our Mission"
      url: "/mission/"
      weight: 1
      parent: "about"
    - identifier: "who-we-are"
      name: "Who We Are"
      url: "/who/"
      weight: 2
      post: "Membership is open to all registered Democrats who share our goals"
      parent: "about"
    - identifier: "meetings-and-events"
      name: "Meetings & Events" 
      url: "/events/"
      weight: 3
    - identifier: "endorsements"
      name: "Endorsements"
      url: "/endorsements/"
      weight: 4
    - identifier: "links"
      name: "Links"
      url: "/links/"
      weight: 5
    - identifier: "contact"
      name: "Contact"
      url: "/contact/"
      weight: 6
es:
  languageName: Spanish
  contentDir: content/es
  weight: 2
  title: "Título del Sitio"
  params:
    description: "Descripción del Sitio"
  menu:
    main:
    - identifier: "about"
      name: "Acerca de"
      url: "/example-page/"
      weight: 1
    - identifier: "child-1"
      name: "Página Hija de Ejemplo"
      url: "/example-page/"
      weight: 1
      parent: "about"
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 3
    - identifier: "blog"
      name: "Blog"
      url: "/blog/"
      weight: 2
